USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::220851193497:role/yt-snowflake-s3-role'
    STORAGE_ALLOWED_LOCATIONS = ('S3://s3-ai-zomato-pipeline-bucket/');


GRANT USAGE ON INTEGRATION ZOMATO_S3_INT TO ROLE DBT_ROLE;

DESCRIBE INTEGRATION ZOMATO_S3_INT;
