USE ROLE ACCOUNTADMIN;
USE DATABASE ZOMATO;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT ZOMATO.RAW.CSV_FMT

    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = (' ', '\\N', 'NULL')
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;
    


 CREATE OR REPLACE STAGE ZOMATO.RAW.ZOMATO_RAW_STAGE
    STORAGE_INTEGRATION = ZOMATO_S3_INT
    URL = 'S3://s3-ai-zomato-pipeline-bucket/raw/'
    FILE_FORMAT = ZOMATO.RAW.CSV_FMT;

-- listing all the subfolder for testing
List @ZOMATO.RAW.ZOMATO_RAW_STAGE;
-- CONNECTION works, so now loading 
